# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UI_SP.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QObject, pyqtSlot

class Ui_MainWindow(QObject):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(110, 40, 641, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lblArchivo = QtWidgets.QLabel(self.frame)
        self.lblArchivo.setGeometry(QtCore.QRect(0, 30, 121, 16))
        self.lblArchivo.setObjectName("lblArchivo")
        self.txtNombreArchivo = QtWidgets.QLineEdit(self.frame)
        self.txtNombreArchivo.setGeometry(QtCore.QRect(130, 30, 371, 21))
        self.txtNombreArchivo.setObjectName("txtNombreArchivo")
        self.btnSubirArchivo = QtWidgets.QPushButton(self.frame)
        self.btnSubirArchivo.setGeometry(QtCore.QRect(520, 90, 113, 32))
        self.btnSubirArchivo.setObjectName("btnSubirArchivo")
        self.btnBuscarArchivo = QtWidgets.QPushButton(self.frame)
        self.btnBuscarArchivo.setGeometry(QtCore.QRect(510, 20, 101, 31))
        self.btnBuscarArchivo.setObjectName("btnBuscarArchivo")
        self.txtResultadoArchivo = QtWidgets.QTextBrowser(self.centralwidget)
        self.txtResultadoArchivo.setGeometry(QtCore.QRect(110, 190, 641, 271))
        self.txtResultadoArchivo.setObjectName("txtResultadoArchivo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)

        #definicion de las funciones de los botones
        self.btnBuscarArchivo.clicked.connect(self.browseSlot)
        self.btnSubirArchivo.clicked.connect(self.writeDocSlot)
        self.txtNombreArchivo.returnPressed.connect(self.returnPressedSlot)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lblArchivo.setText(_translate("MainWindow", "Nombre Del Archivo"))
        self.btnSubirArchivo.setText(_translate("MainWindow", "Subir Archivo"))
        self.btnBuscarArchivo.setText(_translate("MainWindow", "Browser"))
    
    @pyqtSlot()
    def returnPressedSlot(self):
        pass

    @pyqtSlot()
    def browseSlot(self):
        print("hg")
        pass

    @pyqtSlot()
    def writeDocSlot(self):
        pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
